on:
  push:
    branches:
      - master

name: Tests in Docker

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: docker build . -t go-test
    - name: Test
      run: docker run go-test go test ./...