on:
  push:
    branches:
      - master

name: Test Sample Go project

jobs:
  test:
    strategy:
      mystrategy:
        go-version: [1.18.x]
        platform: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ mystrategy.platform }}
    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ mystrategy.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Test
      run: go test pkg/math/*.go