on:
  push:
    branches:
      - master

name: Test Sample Go project

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: go-test
    - name: Test
      run: docker run go-test go test ./...